### ISSUE TITLE
Oregon/British Columbia Is Independent?

### ISSUE THREAD

**Issue by TurtleShroom** [Radsterman/Victorian-Flavor-Mod#32]
Good evening and Merry Christmas.

In the Vanilla rendition of the game, and in most Mods dealing with historical accuracy, British Columbia (with the "ORG" Tag) is listed as a Puppet of the UK. Specifically, this is on line ninety-three.

`
		create_diplomatic_pact = {
			country = c:ORG
			type = puppet
		}		
`

I noticed that in this Mod, British Columbia is entirely independent. I am using the unstable version that supposedly incorporated the HFM Mod, and I found this after looking for a long time. (The HFM Mod notably added the Seminoles in Florida, which your Mod doesn't seem to have.)

Is this intentional? It legitimately makes no sense that the UK would not own British Columbia in 1836 AD.

Thank you for any assistance you may render.

Merry Christmas,
-TURTLESHROOM

**Comment by Radsterman** [comment]
We've swapped the Columbia District to use the British Columbia tag instead of the Oregon tag so that Oregon can be free to form as a separate provisional government, as it did historically. Columbia District has also been changed to be a subject of the Hudson Bay Company instead of being under direct British rule as well. I've been running unstable for a while now and haven't encountered it being independent like you've described. (Also the mod you're describing is HFE, not HFM)
